name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      sa_enable:
        description: 'enable SA App'
        required: true
        default: 'true'
        type: choice
        options:
        - 'true'
        - 'false'

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: yarn install
      - run: yarn lint
      - run: yarn typescript
      - if: github.event.inputs.sa_enable == ''
        run: yarn build
      - if: github.event.inputs.sa_enable == 'true'
        name: enable SA App
        run: |
          yarn build
          echo "custom_message=enable SA feature" >> $GITHUB_ENV
      - if: github.event.inputs.sa_enable == 'false'
        name: disable SA App
        run: |
          yarn build:disable
          echo "custom_message=disable SA feature" >> $GITHUB_ENV
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          yarn deploy -u "github-actions-bot <support+actions@github.com>" -m "${{ github.event.head_commit.message }}${{ env.custom_message }}"